config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'

  resources :users do
    post 'notifications/:id/view', to: 'notifications#view', as: :notification_view
    resources :reminders, only: [:new, :create, :destroy], shallow: true do
      post 'dismiss', to: 'reminders#dismiss', as: :dismiss
    end
    resources :tasks, only: [:index]
    resources :labels, only: [:index]
  end

  resources :tasks do
    post 'request_assistance', to: 'tasks#request_assistance', as: :request_assistance
    post 'accept', to: 'tasks#accept', as: :accept
    post 'start', to: 'tasks#start', as: :start
    post 'mark_complete', to: 'tasks#mark_complete', as: :complete
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end

  resources :labels, only: [:index, :show, :new, :create]

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  delete '/logout', to: 'sessions#destroy'

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :client, class_name: 'User'
  delegate :assistant, to: :client
  has_many :notifications, dependent: :destroy
  has_many :reminders, dependent: :nullify
  has_many :comments, dependent: :destroy
  has_many :labels_tasks
  has_many :labels, through: :labels_tasks, dependent: :destroy

  validates :title, :content, :due_date, :status, presence: true

  STATUSES = [:idle, :requested, :accepted, :in_progress, :completed]
  enum status: STATUSES
  STATUSES.each { |state| alias_method state, :"#{state}?" }

  default_scope { order(:due_date) }

  def request_assistance
    requested!
    send_status_notification_to(assistant)
  end

  def accept
    accepted!
    send_status_notification_to(client)
  end

  def start
    in_progress!
    send_status_notification_to(client)
  end

  def mark_complete
    completed!
    send_status_notification_to(client)
  end

  def delegated?
    ["requested", "accepted", "in_progress"].include?(status)
  end

  def human_due_date
    due_date.strftime("%-I:%M %P %A, %b %-d")
  end

  def send_status_notification_to(user)
    user.notify(self, status_message)
  end

  def status_message
    {
      "idle"        => "A task titled '#{title}' has been created!",
      "requested"   => "#{client.name} requires assistance with '#{title}'.",
      "accepted"    => "Assistance request for '#{title}' has been accepted!",
      "in_progress" => "Work has begun on '#{title}'.",
      "completed"   => "'#{title}' has been completed!"
    }[status]
  end

  def apply_label(label)
    labels << label unless labels.include?(label)
  end

  def labels_attributes=(label_attributes)
    names = label_attributes["0"]["name"].split(",").map(&:strip).reject(&:blank?)
    names.each { |name| apply_label(Label.find_or_create_by(name: name)) }
  end

  def label_ids=(ids)
    labels.clear
    ids.reject(&:blank?).each do |id|
      labels << Label.find(id) unless label_ids.include?(id)
    end
  end

  def num_comments
    comments.count
  end

end

app/models/user.rb
class User < ApplicationRecord

  # As client
  belongs_to :assistant, class_name: 'User', optional: true
  has_many :tasks, foreign_key: :client_id
  has_many :reminders, foreign_key: :client_id
  # added in for the spec.md, just for show
  has_many :labels, through: :tasks

  # As assistant
  has_many :clients, foreign_key: :assistant_id, class_name: 'User'

  # As general user
  has_many :comments, foreign_key: :author_id
  has_many :notifications, foreign_key: :receiver_id

  has_secure_password
  validates :name, :role, presence: true
  validates :email, presence: true, uniqueness: true

  enum role: [:client, :assistant, :admin]

  scope :alphabetical, -> { order(:name) }

  after_create :set_role

  # Assembles all of an assistant's "to-do" tasks (those
  # requested of her by her clients)
  def client_tasks
    Task.joins(:client).where(users: {assistant_id: id}, status: 1..3)
  end

  def client_reminders
    Reminder.joins(:client).where(users: {assistant_id: id})
  end

  # Scopes tasks which have, at some point, been requested
  # of a client's assistant and have not yet been completed
  def delegated_tasks
    tasks.where(status: 1..3)
  end

  def notify(task, message=nil)
    notifications.create(
      task: task,
      content: message || "#{task.title} needs your attention."
    )
  end

  def set_role
    roles = YAML.load_file(Rails.root.join('config', 'roles.yml')) rescue {}
    self.role = roles[email] if roles[email]
    save
  end

  def provider_name
    provider.humanize.split.first.capitalize
  end

  def avatar_url
    color = Random.new(id).rand(16**5...16**6).to_s(16)
    "https://placehold.it/75x75/#{color}"
  end

  class << self

    def from_omniauth(auth)
      where(
        provider: auth['provider'],
        uid:      auth['uid']
      ).first_or_initialize(
        name:     auth['info']['name'],
        email:    auth['info']['email'],
        password: SecureRandom.base64(10)
      )
    end

  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :request_assistance, :accept, :start, :mark_complete]
  before_action :authorize_task, only: [:show, :edit, :update, :destroy, :request_assistance, :accept, :start, :mark_complete]

  def index
    authorize Task
    if params[:user_id]
      @user = User.find(params[:user_id])
      authorize @user, :show?
      @tasks = policy_scope(@user.tasks)
    else
      @tasks = policy_scope(Task)
    end
    @task = current_user.tasks.build
  end

  def show
    respond_to do |format|
      format.html { @comment = @task.comments.build; render :show }
      format.json { render json: @task }
    end
  end

  def edit
    @comments = @task.comments
  end

  def create
    @task = Task.new(task_params)
    authorize @task
    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      @tasks = policy_scope(Task)
      flash_errors_for @task
      render :index
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      flash_errors_for @task
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully deleted.'
  end

  # Maybe the following actions should ultimately be part of #update. But, I
  # think that since notifications should be triggered with the associated
  # method calls on @task, and actions should be kept slim, I would prefer to
  # have these status changes solidified into their own actions, rather than
  # have a big conditional in #update. A redesign might allow notifications to
  # be sent based on status change alone, allowing a slim #update and removal
  # of these paths, but for now I'm going to let it be.

  def request_assistance
    @task.request_assistance
    redirect_to tasks_path, notice: "Assistance with '#{@task.title}' requested!"
  end

  def accept
    @task.accept
    redirect_to tasks_path, notice: "Assistance request for '#{@task.title}' accepted!"
  end

  def start
    @task.start
    redirect_to tasks_path, notice: "'#{@task.title}' is in progress!"
  end

  def mark_complete
    @task.mark_complete
    redirect_to request.referrer, notice: "'#{@task.title}' has been completed!"
  end

  private

    def set_task
      @task = Task.find(params[:task_id] || params[:id])
    end

    def authorize_task
      authorize @task
    end

    def task_params
      params.require(:task).permit(:title, :content, :due_date, :client_id, label_ids: [], labels_attributes: [:name])
    end
end

app/views/tasks/_admin_task_buttons.html.erb
<%= link_to "Remind Client", new_user_reminder_path(task.client, task_id: task.id), class: "btn btn-warning float-right" %>
<%= button_to "Accept Task", task_accept_path(task), class: "btn btn-primary float-right" %>
<%= button_to "Begin Work", task_start_path(task), class: "btn btn-info request-floater" %>
<%= button_to "Mark Complete", task_complete_path(task), class: "btn btn-success float-right" %>

app/views/tasks/_assistant_task_buttons.html.erb
<%= link_to "Remind Client", new_user_reminder_path(task.client, task_id: task.id), class: "btn btn-warning float-right" %>
<% if task.requested? %>
  <%= button_to "Accept Task", task_accept_path(task), class: "btn btn-primary float-right" %>
<% elsif task.accepted? %>
  <%= button_to "Begin Work", task_start_path(task), class: "btn btn-info request-floater" %>
<% elsif task.in_progress? %>
  <%= button_to "Mark Complete", task_complete_path(task), class: "btn btn-success float-right" %>
<% end %>

app/views/tasks/_client_task_buttons.html.erb
<% if task.completed? %>
  <%= button_to "Remove Completed Task", task_path(task), method: :delete, class: "btn btn-danger float-right" %>
<% else %>
  <%= button_to "Mark Complete", task_complete_path(task), class: "btn btn-success float-right" %>
  <%= button_to "Request Assistance", task_request_assistance_path(task), class: "btn btn-primary request-floater" if task.idle? %>
<% end %>

app/views/tasks/_tabs.html.erb
<ul class="nav nav-tabs card-header-tabs">
  <li class="nav-item">
    <%= link_to "Summary", tasks_path + "#task_#{task.id}", data: { task: task.id }, class: "nav-link summary-link #{(current_page?(tasks_path) || current_page?(root_path)) ? "active" : "text-muted"}" %>
  </li>
  <li class="nav-item">
    <%= link_to "View (#{task.comments.any? ? pluralize(task.comments.count, "comment") : "no comments yet"})", task_path(task), data: { task: task.id }, class: "nav-link comments-link #{current_page?(task_path(task)) ? "active" : "text-muted"}" %>
  </li>
  <% if policy(task).update? %>
    <li class="nav-item">
      <%= link_to "Edit", edit_task_path(task), data: { task: task.id }, class: "nav-link edit-link #{current_page?(edit_task_path(task)) ? "active" : "text-muted"}" %>
    </li>
  <% end %>
</ul>

app/views/tasks/_task_card.html.erb
<a id="task_<%= task.id %>" class="task-card-anchor"></a>
<article id="task_card_<%= task.id %>" class="card task-card task_card_<%= task.id %>">

  <div class="card-header">
    <div class="status-circle-area <%= task.status %>">
      <div class="status-circle completed"></div>
      <div class="status-circle in_progress"></div>
      <div class="status-circle accepted"></div>
    </div>
    <h4 class="task-title"><%= task.title %></h4>
    <h6>
      <% task.labels.each do |label| %>
        <%= link_to label.name, label_path(label), class: "text-muted card-link" %>
      <% end %>
    </h6>
    <%= render partial: 'tasks/tabs', locals: {task: task} %>
  </div>

  <div class="card-block">
    <% unless current_user.client? %>
      <h6 class="task-client-header">Task from <%= link_to task.client.name, user_path(task.client) %>:</h6>
    <% end %>
    <p><%= task.content %></p>
  </div>

  <div class="card-footer">
    <span class="task-due-floater text-muted"><em>Due <%= task.human_due_date %></em></span>
    <%= render partial: "tasks/#{current_user.role}_task_buttons", locals: {task: task} %>
  </div>

</article>
<div id="task_comments_<%= task.id %>" class="comment-section task_comments_<%= task.id %>">
</div>

app/views/tasks/_task_form_card.html.erb
<%= form_for task do |f| %>
  <div class="card-group new-task-card-group">
    <div class="card left-card col-md-8">

      <%= f.hidden_field :client_id %>

      <div class="card-header <%= "no-" unless tabs %>tabs-height">
        <%= f.text_field :title, placeholder: "Task title", class: "new-task-title" %>
        <%= render partial: 'tasks/tabs', locals: {task: task} if tabs %>
      </div>

      <div class="card-block">
        <%= f.text_area :content, placeholder: "What needs to be done?", class: "new-task-content", rows: 6 %>
      </div>

      <div class="card-footer card-group-footer-left">
        <span class="float-left form-inline">
          <span class="extra-info">Due:&nbsp;</span>
          <%= f.datetime_select :due_date,
          {
            start_year: Time.now.year,
            order: [:month, :day, :year],
            default: 2.hours.from_now.localtime,
            ampm: true,
            minute_step: 15
          },
          {
            class: "form-control"
          } %>
        </span>
      </div>
    </div>

    <div class="card right-card col-md-4">

      <div class="card-header label-header text-center <%= "no-" unless tabs %>tabs-height">
        Labels (<%= user_os_mac? ? "⌘" : "ctrl" %> + click for multiple)<br>
        <em><%= link_to "or, create new labels", new_label_path %></em>
      </div>

      <div class="card-block <%= "tabs-height" if tabs %>">
        <%= f.collection_select :label_ids, Label.all, :id, :name, {}, {class: "label-select", multiple: true, size: 4} %>
        <div class="new-labels-label text-center">More labels: <span class="extra-info">(separate with commas)</span></div>
        <div class="new-labels-input">
          <%= f.fields_for :labels, task.labels.build do |lbl| %>
            <%= lbl.text_field :name %>
          <% end %>
        </div>
      </div>

      <div class="card-footer card-group-footer-right">
        <%= f.submit class: "btn btn-primary float-right" %>
      </div>

    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render partial: 'task_form_card', locals: {task: @task, tabs: true} %>
<div class="row">
  <div class="col-md-10 offset-md-1">
    <%= render partial: 'comments/comment_card', collection: @comments, as: :comment %>
  </div>
</div>

app/views/tasks/index.html.erb
<h2 class="text-center main-heading">
  <% if @user %>
    <%= @user.name -%>'s tasks
  <% else %>
    <%= current_user.client? ? "#{current_user.name}'s" : "Client" %> tasks
  <% end %>
</h2>

<%= render partial: 'task_form_card', locals: {task: @task, tabs: false} if policy(@task).create? %>

<%= render partial: 'task_card', collection: @tasks, as: :task, locals: {tab: :index} %>

app/views/tasks/show.html.erb
<%= render partial: 'tasks/task_card', locals: {task: @task, tab: :show} %>
<div class="row">
  <div class="col-md-10 offset-md-1">
    <%= render partial: 'comments/comment_card', collection: @task.comments.select(&:persisted?), as: :comment %>
    <%= render partial: 'comments/comment_form_card', locals: {task: @task, comment: @comment} %>
  </div>
</div>