config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'

  resources :users do
    post 'notifications/:id/view', to: 'notifications#view', as: :notification_view
    resources :reminders, only: [:new, :create, :destroy], shallow: true do
      post 'dismiss', to: 'reminders#dismiss', as: :dismiss
    end
    resources :tasks, only: [:index]
    resources :labels, only: [:index]
  end

  resources :tasks do
    post 'request_assistance', to: 'tasks#request_assistance', as: :request_assistance
    post 'accept', to: 'tasks#accept', as: :accept
    post 'start', to: 'tasks#start', as: :start
    post 'mark_complete', to: 'tasks#mark_complete', as: :complete
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end

  resources :labels, only: [:index, :show, :new, :create]

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  delete '/logout', to: 'sessions#destroy'

end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :client, class_name: 'User'
  delegate :assistant, to: :client
  belongs_to :task, optional: true

  validates :content, :status, presence: true

  enum status: [:unseen, :seen, :dismissed]

  scope :not_dismissed, -> { where.not(status: :dismissed).order(created_at: :desc) }
  scope :dismissed, -> { where(status: :dismissed).order(updated_at: :desc) }

  def view
    seen!
  end

  def dismiss
    dismissed!
  end

  def human_created_at
    created_at.strftime("%a, %b %-d - %-I:%M %P")
  end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:dismiss, :destroy]
  before_action :authorize_reminder, only: [:dismiss, :destroy]
  before_action :set_user, only: [:new, :create]

  def new
    @reminder = @user.reminders.build(task_id: params[:task_id])
    authorize @reminder
  end

  def create
    @reminder = @user.reminders.build(reminder_params)
    authorize @reminder
    if @reminder.save
      redirect_to tasks_path, notice: "Reminder sent."
    else
      flash_errors_for @reminder
      render :new
    end
  end

  def destroy
    @reminder.destroy
    redirect_to root_path, alert: "Reminder successfully removed."
  end

  def dismiss
    @reminder.dismiss
    redirect_to request.referrer, notice: "Reminder dismissed."
  end

  private

    def set_reminder
      @reminder = Reminder.find(params[:reminder_id] || params[:id])
    end

    def authorize_reminder
      authorize @reminder
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def reminder_params
      params.require(:reminder).permit(:content, :task_id)
    end

end

app/views/reminders/_form.html.erb
<%= form_for [user, reminder] do |f| %>
  <article class="card new-reminder-card">
    <div class="card-header">
      <h4>Send <%= user.name %> a reminder</h4>
    </div>
    <%= f.text_area :content, rows: 3, placeholder: "Write your reminder here..." %>
    <%= f.collection_select :task_id, user.delegated_tasks, :id, :title, {include_blank: "Select an associated task (optional)"}, class: "form-control concerning-task" %>
    <div class="card-footer">
      <%= f.submit "Send Reminder", class: "btn btn-primary float-right" %>
    </div>
  </article>
<% end %>

app/views/reminders/_reminder_card.html.erb
<article class="card reminder-card <%= reminder.status %>">
  <ul class="list-group list-group-flush">
    <li class="list-group-item reminder-content"><%= reminder.dismissed? ? content_tag(:em, reminder.content) : reminder.content %></li>
    <%= content_tag(:li, raw("Sent to&nbsp;#{link_to reminder.client.name, user_path(reminder.client)}"), class: "list-group-item reminder-client") unless current_user.client? %>
    <li class="list-group-item reminder-created-at"><%= reminder.human_created_at %></li>
    <%= link_to content_tag(:li, "Concerning '#{reminder.task.title}' #{'(' + reminder.task.status.humanize.downcase + ')'}", class: "list-group-item reminder-task task-#{reminder.task.status}"), task_path(reminder.task), class: "concerning-link" if reminder.task %>
  </ul>
  <% unless reminder.dismissed? %>
    <div class="card-footer">
      <%= button_to "Undo", reminder_path(reminder), method: :delete, class: "btn btn-danger float-right" if policy(reminder).destroy? %>
      <%= button_to "Dismiss", reminder_dismiss_path(reminder), class: "btn btn-danger float-right" if policy(reminder).dismiss? %>
    </div>
  <% end %>
</article>

app/views/reminders/_sidebar.html.erb
<h3 id="reminders-header" class="text-center">Reminders</h3>

<div class="reminders-nav-area">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a href="" class="nav-link active" id="new-reminders-tab-link"><%= current_user.client? ? "New" : "Sent" %></a>
    </li>
    <li class="nav-item">
      <a href="" class="nav-link text-muted" id="dismissed-reminders-tab-link">Dismissed<%= " by client" unless current_user.client? %></a>
    </li>
  </ul>
</div>

<div class="reminder-card-list" id="new-reminder-card-list">

  <% if current_user.assistant? %>
    <ul class="reminder-link-list">
      <% current_user.clients.each do |client| %>
        <li><%= link_to "Send a reminder to #{client.name}", new_user_reminder_path(client) %></li>
      <% end %>
    </ul>
  <% end %>

  <%= render partial: 'reminders/reminder_card', collection: reminders.not_dismissed, as: :reminder %>
  
</div>

<div class="reminder-card-list hidden-xs-up" id="dismissed-reminder-card-list">
  <%= render partial: 'reminders/reminder_card', collection: reminders.dismissed, as: :reminder %>
</div>

app/views/reminders/new.html.erb
<h2 class="text-center main-heading">New reminder from <%= current_user.name %></h2>

<%= render partial: 'form', locals: {user: @user, reminder: @reminder} %>