config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'

  resources :users do
    post 'notifications/:id/view', to: 'notifications#view', as: :notification_view
    resources :reminders, only: [:new, :create, :destroy], shallow: true do
      post 'dismiss', to: 'reminders#dismiss', as: :dismiss
    end
    resources :tasks, only: [:index]
    resources :labels, only: [:index]
  end

  resources :tasks do
    post 'request_assistance', to: 'tasks#request_assistance', as: :request_assistance
    post 'accept', to: 'tasks#accept', as: :accept
    post 'start', to: 'tasks#start', as: :start
    post 'mark_complete', to: 'tasks#mark_complete', as: :complete
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end

  resources :labels, only: [:index, :show, :new, :create]

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  delete '/logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ApplicationRecord

  # As client
  belongs_to :assistant, class_name: 'User', optional: true
  has_many :tasks, foreign_key: :client_id
  has_many :reminders, foreign_key: :client_id
  # added in for the spec.md, just for show
  has_many :labels, through: :tasks

  # As assistant
  has_many :clients, foreign_key: :assistant_id, class_name: 'User'

  # As general user
  has_many :comments, foreign_key: :author_id
  has_many :notifications, foreign_key: :receiver_id

  has_secure_password
  validates :name, :role, presence: true
  validates :email, presence: true, uniqueness: true

  enum role: [:client, :assistant, :admin]

  scope :alphabetical, -> { order(:name) }

  after_create :set_role

  # Assembles all of an assistant's "to-do" tasks (those
  # requested of her by her clients)
  def client_tasks
    Task.joins(:client).where(users: {assistant_id: id}, status: 1..3)
  end

  def client_reminders
    Reminder.joins(:client).where(users: {assistant_id: id})
  end

  # Scopes tasks which have, at some point, been requested
  # of a client's assistant and have not yet been completed
  def delegated_tasks
    tasks.where(status: 1..3)
  end

  def notify(task, message=nil)
    notifications.create(
      task: task,
      content: message || "#{task.title} needs your attention."
    )
  end

  def set_role
    roles = YAML.load_file(Rails.root.join('config', 'roles.yml')) rescue {}
    self.role = roles[email] if roles[email]
    save
  end

  def provider_name
    provider.humanize.split.first.capitalize
  end

  def avatar_url
    color = Random.new(id).rand(16**5...16**6).to_s(16)
    "https://placehold.it/75x75/#{color}"
  end

  class << self

    def from_omniauth(auth)
      where(
        provider: auth['provider'],
        uid:      auth['uid']
      ).first_or_initialize(
        name:     auth['info']['name'],
        email:    auth['info']['email'],
        password: SecureRandom.base64(10)
      )
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:show, :edit, :update, :destroy]

  def index
    authorize User
    @users = policy_scope(User)
  end

  def show
  end

  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User was successfully created.'
    else
      flash_errors_for @user
      render :new
    end
  end

  def update
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render json: @user }
      end
    else
      flash_errors_for @user
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def authorize_user
      authorize @user
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :assistant_id)
    end
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autocomplete: "name", required: true, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :email %>
    <%= f.email_field :email, required: true, class: "form-control" %>
  </div>

  <% if user.new_record? %>
    <div class="field form-group">
      <%= f.label :password %>
      <%= f.password_field :password, required: true, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :password_confirmation, "Confirm password" %>
      <%= f.password_field :password_confirmation, required: true, class: "form-control" %>
    </div>
  <% end %>

  <% unless user.assistant? %>
    <div class="field form-group">
      <%= f.label :assistant_id, "Assistant" %>
      <%= f.collection_select :assistant_id, User.assistant, :id, :name, {prompt: "Select an assistant"}, class: "form-control" %>
    </div>
  <% end %>

  <div class="form-group">
    <br><%= f.submit(user.new_record? ? "Sign up" : "Save", class: "btn btn-primary") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', @user %> |
<%= link_to 'Users', users_path %>

app/views/users/index.html.erb
<h2 class="text-center main-heading">Users</h2>

<div class="card users-card">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Assistant</th>
        <th colspan="3" class="text-center">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @users.alphabetical.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.role %></td>
          <!-- hot damn, look at this terrible nested ternary conditional -->
          <td><%= user.client? ? (policy(user.assistant).show? ? link_to(user.assistant.name, user_path(user.assistant)) : user.assistant.name) : "N/A" %></td>
          <td><%= link_to 'Show', user if policy(user).show? %></td>
          <td><%= link_to 'Edit', edit_user_path(user) if policy(user).update? %></td>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } if policy(user).destroy? %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div id="user-card" class="card user-card" data-user="<%= @user.id %>">
  <h4>Name</h4>
  <p class="editable" data-type="name"><%= @user.name %> <em>(<%= @user.role %>)</em></p>
  <input type="text" style="display: none;" class="form-control user-info user-info-name col-md-11 ml-4" name="user[name]" value="<%= @user.name %>">
  <h4>Email</h4>
  <p class="editable" data-type="email"><%= @user.email %></p>
  <input type="text" style="display: none;" class="form-control user-info user-info-email col-md-11 ml-4" name="user[email]" value="<%= @user.email %>">

  <% if @user.client? %>

    <h4>Assistant</h4>
    <p><%= @user.assistant.name %></p>

  <% else %>

    <h4>Clients</h4>
    <ul>
      <% @user.clients.each do |client| %>
        <%= content_tag(:li, policy(client).show? ? link_to(client.name, user_path(client)) : client.name) %>
      <% end %>
    </ul>

  <% end %>

  <p><%= link_to('Edit', edit_user_path(@user)) + " | " if policy(@user).update? %><%= link_to 'Users', users_path %></p>

</div>

<%= render partial: 'tasks/task_card', collection: policy_scope(@user.tasks), as: :task, locals: {tab: :index} %>