config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'

  resources :users do
    post 'notifications/:id/view', to: 'notifications#view', as: :notification_view
    resources :reminders, only: [:new, :create, :destroy], shallow: true do
      post 'dismiss', to: 'reminders#dismiss', as: :dismiss
    end
    resources :tasks, only: [:index]
    resources :labels, only: [:index]
  end

  resources :tasks do
    post 'request_assistance', to: 'tasks#request_assistance', as: :request_assistance
    post 'accept', to: 'tasks#accept', as: :accept
    post 'start', to: 'tasks#start', as: :start
    post 'mark_complete', to: 'tasks#mark_complete', as: :complete
    resources :comments, only: [:index, :create, :destroy], shallow: true
  end

  resources :labels, only: [:index, :show, :new, :create]

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  delete '/logout', to: 'sessions#destroy'

end

app/views/layouts/_messages.html.erb
<section id="messages">
  <%= content_tag(:div, flash[:error], :id => "flash_error", class: "alert alert-danger") if flash[:error] %>
  <%= content_tag(:div, flash[:notice], :id => "flash_notice", class: "alert alert-info") if flash[:notice] %>
  <%= content_tag(:div, flash[:alert], :id => "flash_alert", class: "alert alert-warning") if flash[:alert] %>
  <%= content_tag(:div, flash[:message], :id => "flash_message", class: "alert alert-success") if flash[:message] %>
</section>

app/views/layouts/_top_bar.html.erb
<nav id="top-bar" class="navbar navbar-light navbar-toggleable-md">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapsible">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Cadu", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarCollapsible">
    <div class="navbar-nav">
      <% if logged_in? %>
        <%= link_to "Tasks", tasks_path, class: "nav-item nav-link #{"active" if current_page?(tasks_path) || current_page?(root_path)}" %>
        <%= link_to "Labels", labels_path, class: "nav-item nav-link #{"active" if current_page?(labels_path)}" %>
        <%= link_to "My Profile", user_path(current_user), class: "nav-item nav-link #{"active" if current_page?(user_path(current_user))}" %>
        <%= link_to "User Pages", users_path, class: "nav-item nav-link #{"active" if current_page?(users_path)}" unless current_user.client? %>
        <%= link_to "Log out", logout_path, method: :delete, class: "nav-item nav-link" %>
      <% else %>
        <%= link_to "Log in", login_path, class: "nav-item nav-link #{"active" if current_page?(login_path)}" %>
        <%= link_to "Sign up", signup_path, class: "nav-item nav-link #{"active" if current_page?(signup_path)}" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Cadu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/top_bar' %>

    <main class="container-fluid">

      <div class="row">

        <% if logged_in? %>
          <div class="col-md-2 sidebar notification-sidebar">
            <%= render partial: "notifications/sidebar", locals: {notifications: policy_scope(Notification).viewing_order} %>
          </div>

          <div class="col-md-7">
            <%= render partial: 'layouts/messages' %>
            <%= yield %>
          </div>

          <div class="col-md-3 sidebar reminder-sidebar">
            <%= render partial: "reminders/sidebar", locals: {reminders: policy_scope(Reminder)} %>
          </div>

        <% else %>

          <div class="col-md-8 offset-md-2 non-user-area">
            <%= render partial: 'layouts/messages' %>
            <%= yield %>
          </div>

        <% end %>
      </div>

    </main>

    <%# this is silly; this layout shouldn't be used this way %>
    <% if logged_in? %>
      <script id="comments-template" type="text/x-handlebars-template">
        <%= render partial: 'comments/handlebars/comments' %>
      </script>

      <script id="comment-card-partial" type="text/x-handlebars-template">
        <%= render partial: 'comments/handlebars/comment_card' %>
      </script>

      <script id="comment-form-card-partial" type="text/x-handlebars-template">
        <%= render partial: 'comments/handlebars/comment_form_card' %>
      </script>

      <script id="floating-task-card-template" type="text/x-handlebars-template">
        <%= render partial: 'tasks/handlebars/task_card' %>
      </script>

      <script id="floating-task-card-tabs-partial" type="text/x-handlebars-template">
        <%= render partial: 'tasks/handlebars/tabs' %>
      </script>
    <%- end %>

    <!-- <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="/reminders.js"></script>
  </body>
</html>